services:
  nextjs:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install --legacy-peer-deps && npm run dev"
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - next-cache:/app/.next
    environment:
      - NODE_ENV=development
      - POCKETBASE_URL=http://pocketbase:8090
      - PB_TYPEGEN_URL=http://pocketbase:8090
    depends_on:
      pocketbase:
        condition: service_healthy
    env_file:
      - .env.development
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    ports:
      - "8090:8090"
    volumes:
      - pocketbase_data:/pb_data
      - pocketbase_public:/pb_public
      # Comment out hooks volume if not actively using hooks
      # - ./pocketbase/pb_hooks:/pb_hooks
    environment:
      - TZ=UTC
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    command: ["--hooksDir", "/pb_hooks"]

volumes:
  pocketbase_data:
  pocketbase_public:
  node_modules:
  next-cache:
