version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - POCKETBASE_URL=http://pocketbase:8090
      - PB_TYPEGEN_URL=http://pocketbase:8090
    depends_on:
      - pocketbase
    env_file:
      - .env.production
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    ports:
      - "8090:8090"
    volumes:
      - pocketbase_data:/pb_data
      - pocketbase_public:/pb_public
    environment:
      - TZ=UTC
    restart: unless-stopped
    healthcheck:
      test: |
        wget --no-verbose --tries=1 --spider http://localhost:8090/api/health ||
        exit 1
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pocketbase_data:
  pocketbase_public:
